Feature - use behaviours
UKHomeOfficeForms/hof-form-wizard pull request #9
Opened 2017-02-14 10:24 UTC by joefitter

This PR removes the dependency on hof-controllers and instead installs hof-form-controller ^3.0.1 which already has hooks and session IO mixed in. Also installed mixwith.js so steps can now provide one or more custom "behaviours" in place of a singular custom controller. Custom controllers are still supported but a deprication warning is now shown if a custom controller is used.

2017-02-14 12:26 UTC, easternbloc approved these changes
LGTM

2017-02-14 12:50 UTC, joefitter commented
@lennym would like your input if you get time, tomorrow is fine though

2017-02-14 15:12 UTC, lennym requested changes

2017-02-14 15:12 UTC, lennym commented on README.md
> +* `behaviours` - A single behaviour, or an array of behaviours to be mixed into the base controller to extend functionality.
Is the order of behaviours significant when passed as an array? My guess is yes, so I'd probably want to know if they are going to be applied left-to-right or right-to-left.

2017-02-14 15:12 UTC, lennym commented on README.md
> +  }
I don't feel like this is necessarily the *best* example as it extends the constructor, which isn't a common case. I'd either change it to one with a method extension or at least add an example with method extension.

2017-02-14 15:12 UTC, lennym commented on lib/wizard.js
> +  return class extends (_mix = mix(SuperClass)).with.apply(_mix, behaviours) {};
This feels a little like "one line for the sake of being one line". Looking at it, I think this is equivalent:

```js
const _mix = mix(SuperClass);
return class extends _mix.with.apply(_mix, behaviours) {};
```

2017-02-14 15:12 UTC, lennym commented
Looks pretty good overall. I just have a few minor points and clarifications. The biggest thing for me is being clear on what order behaviours get mounted in.

2017-02-14 15:14 UTC, lennym commented on package.json
> -    "hof-controllers": "^6.0.0",
Does this now make `hof-controllers` officially legacy?

2017-02-14 15:20 UTC, lennym commented on package.json
> -    "hof-controllers": "^6.0.0",
:tada:

2017-02-14 16:23 UTC, joefitter commented on README.md
> +  }
Yeah I agree - I was being lazy and just modified the existing example - I'll change it

2017-02-14 16:24 UTC, joefitter commented on lib/wizard.js
> +  return class extends (_mix = mix(SuperClass)).with.apply(_mix, behaviours) {};
whatswrongwithcrammingeverythingtogether?

2017-02-14 16:34 UTC, joefitter commented on package.json
> -    "hof-controllers": "^6.0.0",
![](https://media.makeameme.org/created/oh-yeah-gimmie.jpg)

2017-02-14 17:04 UTC, joefitter commented
@lennym howzat?

2017-02-15 12:36 UTC, lennym requested changes

2017-02-15 12:36 UTC, lennym commented on package.json
> +    "proxyquire": "^1.7.11",
This doesn't seem to be used anywhere - or at least hasn't been added elsewhere in this PR - is it a linting thing?

2017-02-15 12:52 UTC, easternbloc commented on package.json
> +    "proxyquire": "^1.7.11",
You're right this shouldn't be here it's not used.

2017-02-15 14:05 UTC, joefitter commented on package.json
> +    "proxyquire": "^1.7.11",
nope it aint no more 🔥

2017-02-15 14:23 UTC, lennym commented on README.md
> +* `behaviours` - A single behaviour, or an array of behaviours to be mixed into the base controller to extend functionality. If an array of behaviours is given, they are applied left-to-right, so cal
If we're going to deprecate `controller` as a step option then maybe it's a good idea to use npmjs.com/deprecate to output a message if one is passed.

2017-02-15 14:25 UTC, easternbloc commented on README.md
> +* `behaviours` - A single behaviour, or an array of behaviours to be mixed into the base controller to extend functionality. If an array of behaviours is given, they are applied left-to-right, so cal
Seems like a nice idea.

2017-02-15 14:30 UTC, joefitter commented on README.md
> +* `behaviours` - A single behaviour, or an array of behaviours to be mixed into the base controller to extend functionality. If an array of behaviours is given, they are applied left-to-right, so cal
ah yeah, that's nicer - I just added a couple of `console.warns`

2017-02-15 14:32 UTC, lennym commented on README.md
> +* `behaviours` - A single behaviour, or an array of behaviours to be mixed into the base controller to extend functionality. If an array of behaviours is given, they are applied left-to-right, so cal
Oh right, I hadn't spotted that. `console.warn` is *probably* fine, `deprecate` just is a bit less spammy and a bit more colourful.

2017-02-15 14:41 UTC, joefitter commented
@lennym @JoeChapman @easternbloc updated - I removed the test as its _just_ for a deprecation warning - stubbing the console was trivial, but stubbing deprecate would require re-installing proxyquire, which seems like overkill for a warning

2017-02-15 14:41 UTC, lennym commented
That is 100% fine by me.

2017-02-15 14:41 UTC, lennym approved these changes

2017-02-15 14:47 UTC, merged

2017-02-15 14:47 UTC, joefitter commented
![](https://media.giphy.com/media/l46CkATpdyLwLI7vi/giphy.gif)

2017-02-15 14:48 UTC, lennym commented
![](https://media.giphy.com/media/3o7qDSOvfaCO9b3MlO/giphy.gif)

2017-02-15 14:52 UTC, easternbloc commented
@joefitter i love that guy he's the happiest little birthday person on the planet

2017-02-15 14:52 UTC, joefitter commented
It is literally my favourite gif ever